name: CI

on: [pull_request, push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.6, 2.7 ]
    runs-on: ubuntu-latest
    env:
      TESTING: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: ruby -v && echo $TESTING
