name: CI

on: [pull_request, push]

jobs:
  test:
    name: 'Ruby: ${{ matrix.ruby }}, Rails: ${{ matrix.env.RAILS_VERSION }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 2.6
            allow_failure: true
            env:
              RAILS_VERSION: '~> 6.0.0'
            JRUBY_OPT: '--dev'
          - ruby: 2.7
            env:
              RAILS_VERSION: '~> 6.2.0'
              JRUBY_OPT: '--devd'
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Set ENV variables
        env: ${{ matrix.env }}
        run: eho "Hello"
        continue-on-error: ${{ matrix.allow_failure || false }}
      - name: Set ENV variables
        env: ${{ matrix.env }}
        run: echo "Hello"
