name: CI

on: [pull_request, push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 2.6
            RAILS_VERSION: '~> 6.0.0'
            JRUBY_OPT: '--dev'
          - ruby: 2.7
            RAILS_VERSION: '~> 6.2.0'
            JRUBY_OPT: '--devd'
    runs-on: ubuntu-latest
    env:
      TESTING: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Set ENV variables
      env:
        RAILS_VERSION: ${{matrix.RAILS_VERSION}}
        JRUBY_OPT: ${{matrix.JRUBY_OPT}}
      run: ruby -v && echo $TESTING && echo $RAILS_VERSION && $JRUBY_OPT
