name: CI

on: [pull_request, push]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest]
        ruby: [2.6, 2.7]
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }} sample
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: |
        ruby -v
        echo $PATH
        export JRUBY_OPTS='--dev'

    - name: update_rubygems_and_install_bundler
      run: script/update_rubygems_and_install_bundler && unset _JAVA_OPTIONS

    - name: Clone all RSpec repos
      run: script/clone_all_rspec_repos

    - name: bundle install
      run: bundle install --jobs 4 --retry 3 --binstubs --standalone --without documentation --path ../bundle
      shell: bash

    - name: run RSpec build
      run: script/run_build
      shell: bash
